<?php

namespace App\OpenApi;

use OpenApi\Attributes as OA;

#[OA\Info(title: 'API Mobile de Ponto Chags', version: '1.0.0', description: 'API REST para liberação do aplicativo, autenticação JWT, validação do dispositivo, biometria facial, registro de ponto e ajustes manuais.')]
#[OA\Server(url: '/api/v1', description: 'API versão 1')]
#[OA\SecurityScheme(securityScheme: 'bearerAuth', type: 'http', scheme: 'bearer', bearerFormat: 'JWT', description: 'Informe o JWT recebido após validar o código do WhatsApp.')]
#[OA\Tag(name: 'Liberação do aplicativo', description: 'Validação do telefone e emissão do primeiro JWT.')]
#[OA\Tag(name: 'Autenticação', description: 'Sessão e dados do usuário autenticado.')]
#[OA\Tag(name: 'Dispositivos', description: 'Cadastro, atestação e validação do aparelho.')]
#[OA\Tag(name: 'Biometria facial', description: 'Primeiro acesso usando FACEIO.')]
#[OA\Tag(name: 'Ponto', description: 'Consulta e registro de batidas.')]
#[OA\Tag(name: 'Cartão de ponto', description: 'Espelho mensal do cartão.')]
#[OA\Tag(name: 'Ajustes de ponto', description: 'Batidas manuais sujeitas à aprovação do gestor.')]
class MobileApi
{
    #[OA\Post(path: '/app-unlock/whatsapp/request', operationId: 'solicitarCodigoWhatsApp', summary: 'Solicitar código pelo WhatsApp', description: 'Se o número estiver validado no cadastro, envia um código de seis dígitos. A resposta é igual para telefones cadastrados e desconhecidos.', tags: ['Liberação do aplicativo'], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['phone', 'device_installation_id'], properties: [
        new OA\Property(property: 'phone', type: 'string', maxLength: 30, example: '(11) 99999-9999', description: 'Telefone brasileiro ou internacional E.164.'),
        new OA\Property(property: 'device_installation_id', type: 'string', format: 'uuid', example: '550e8400-e29b-41d4-a716-446655440000', description: 'UUID persistente gerado pelo aplicativo.'),
    ])), responses: [
        new OA\Response(response: 202, description: 'Solicitação aceita.', content: new OA\JsonContent(example: ['message' => 'Se o telefone estiver cadastrado, enviaremos um código.', 'data' => ['challenge_id' => '01J...', 'expires_in' => 300, 'resend_after' => 60]])),
        new OA\Response(response: 422, description: 'Campos inválidos.'), new OA\Response(response: 429, description: 'Limite excedido.'),
    ])]
    public function requestWhatsAppCode(): void {}

    #[OA\Post(path: '/app-unlock/whatsapp/verify', operationId: 'validarCodigoWhatsApp', summary: 'Validar código e receber JWT', tags: ['Liberação do aplicativo'], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['challenge_id', 'device_installation_id', 'code'], properties: [
        new OA\Property(property: 'challenge_id', type: 'string', example: '01J...', description: 'ID devolvido na solicitação.'),
        new OA\Property(property: 'device_installation_id', type: 'string', format: 'uuid', example: '550e8400-e29b-41d4-a716-446655440000'),
        new OA\Property(property: 'code', type: 'string', pattern: '^\\d{6}$', example: '123456', description: 'Código recebido no WhatsApp.'),
    ])), responses: [
        new OA\Response(response: 200, description: 'Código validado e JWT emitido.', content: new OA\JsonContent(example: ['data' => ['access_token' => 'eyJ0eXAi...', 'token_type' => 'Bearer', 'expires_in' => 3600, 'app_unlocked' => true, 'first_access' => false, 'requires_face_enrollment' => false]])),
        new OA\Response(response: 404, description: 'Desafio não encontrado.'), new OA\Response(response: 422, description: 'Código inválido, expirado ou consumido.'),
    ])]
    public function verifyWhatsAppCode(): void {}

    #[OA\Get(path: '/me', operationId: 'consultarMeuUsuario', summary: 'Consultar usuário autenticado', security: [['bearerAuth' => []]], tags: ['Autenticação'], responses: [new OA\Response(response: 200, description: 'Dados do usuário.', content: new OA\JsonContent(example: ['data' => ['id' => 10, 'name' => 'Ana Botafogo', 'email' => 'ana@empresa.com.br', 'whatsapp_phone' => '+5511*****9999', 'tracks_time' => true, 'first_access_completed' => true]])), new OA\Response(response: 401, description: 'JWT ausente, inválido ou expirado.')])]
    public function me(): void {}

    #[OA\Post(path: '/auth/refresh', operationId: 'renovarToken', summary: 'Renovar JWT', security: [['bearerAuth' => []]], tags: ['Autenticação'], responses: [new OA\Response(response: 200, description: 'Novo JWT.', content: new OA\JsonContent(example: ['data' => ['access_token' => 'eyJ0eXAi...', 'token_type' => 'Bearer', 'expires_in' => 3600]])), new OA\Response(response: 401, description: 'JWT inválido.')])]
    public function refresh(): void {}

    #[OA\Post(path: '/auth/logout', operationId: 'encerrarSessao', summary: 'Encerrar sessão', security: [['bearerAuth' => []]], tags: ['Autenticação'], responses: [new OA\Response(response: 200, description: 'JWT invalidado.', content: new OA\JsonContent(example: ['message' => 'Sessão encerrada com sucesso.'])), new OA\Response(response: 401, description: 'JWT inválido.')])]
    public function logout(): void {}

    #[OA\Post(path: '/devices/challenges', operationId: 'criarDesafioDispositivo', summary: 'Criar desafio criptográfico', security: [['bearerAuth' => []]], tags: ['Dispositivos'], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['installation_id', 'platform', 'purpose'], properties: [
        new OA\Property(property: 'installation_id', type: 'string', format: 'uuid', example: '550e8400-e29b-41d4-a716-446655440000'),
        new OA\Property(property: 'platform', type: 'string', enum: ['android', 'ios'], example: 'android'),
        new OA\Property(property: 'purpose', type: 'string', enum: ['register', 'verify', 'sensitive_action'], example: 'register', description: 'Finalidade do desafio.'),
    ])), responses: [new OA\Response(response: 201, description: 'Desafio criado.', content: new OA\JsonContent(example: ['data' => ['challenge_id' => '01J...', 'nonce' => 'valor-aleatorio', 'expires_at' => '2026-08-25T22:10:00-03:00', 'required_attestation' => 'play_integrity']])), new OA\Response(response: 422, description: 'Campos inválidos.')])]
    public function deviceChallenge(): void {}

    #[OA\Post(path: '/devices/register', operationId: 'registrarDispositivo', summary: 'Registrar dispositivo e chave pública', description: 'A assinatura deve usar a chave privada ES256 mantida no armazenamento seguro do aparelho.', security: [['bearerAuth' => []]], tags: ['Dispositivos'], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/RegistroDispositivo')), responses: [new OA\Response(response: 201, description: 'Dispositivo registrado.', content: new OA\JsonContent(ref: '#/components/schemas/RespostaDispositivo')), new OA\Response(response: 422, description: 'Assinatura, atestação ou campos inválidos.')])]
    public function registerDevice(): void {}

    #[OA\Post(path: '/devices/verify', operationId: 'verificarDispositivo', summary: 'Revalidar dispositivo cadastrado', security: [['bearerAuth' => []]], tags: ['Dispositivos'], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/VerificacaoDispositivo')), responses: [new OA\Response(response: 200, description: 'Dispositivo validado.', content: new OA\JsonContent(ref: '#/components/schemas/RespostaDispositivo')), new OA\Response(response: 403, description: 'Dispositivo bloqueado.'), new OA\Response(response: 422, description: 'Assinatura ou atestação inválida.')])]
    public function verifyDevice(): void {}

    #[OA\Get(path: '/devices', operationId: 'listarDispositivos', summary: 'Listar meus dispositivos', security: [['bearerAuth' => []]], tags: ['Dispositivos'], responses: [new OA\Response(response: 200, description: 'Lista de dispositivos.', content: new OA\JsonContent(properties: [new OA\Property(property: 'data', type: 'array', items: new OA\Items(ref: '#/components/schemas/Dispositivo'))]))])]
    public function devices(): void {}

    #[OA\Delete(path: '/devices/{device}', operationId: 'revogarDispositivo', summary: 'Revogar dispositivo', security: [['bearerAuth' => []]], tags: ['Dispositivos'], parameters: [new OA\Parameter(name: 'device', in: 'path', required: true, description: 'ID ULID do dispositivo.', schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Dispositivo revogado.'), new OA\Response(response: 404, description: 'Dispositivo não encontrado.')])]
    public function revokeDevice(): void {}

    #[OA\Post(path: '/face-auth/enrollment-sessions', operationId: 'criarSessaoFaceio', summary: 'Iniciar cadastro facial', security: [['bearerAuth' => []]], tags: ['Biometria facial'], parameters: [new OA\Parameter(name: 'X-Device-ID', in: 'header', required: true, description: 'ID do dispositivo registrado.', schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 201, description: 'Sessão criada.', content: new OA\JsonContent(example: ['data' => ['session_id' => '01J...', 'faceio_public_id' => 'fio...', 'payload' => 'valor-opaco', 'expires_at' => '2026-08-25T22:20:00-03:00']])), new OA\Response(response: 503, description: 'FACEIO não habilitado.')])]
    public function faceioSession(): void {}

    #[OA\Post(path: '/face-auth/confirm', operationId: 'confirmarCadastroFaceio', summary: 'Confirmar cadastro facial', security: [['bearerAuth' => []]], tags: ['Biometria facial'], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['session_id'], properties: [new OA\Property(property: 'session_id', type: 'string', example: '01J...')])), responses: [new OA\Response(response: 200, description: 'Cadastro confirmado e JWT liberado.'), new OA\Response(response: 422, description: 'Sessão não confirmada ou expirada.')])]
    public function confirmFaceio(): void {}

    #[OA\Post(path: '/webhooks/faceio', operationId: 'receberWebhookFaceio', summary: 'Receber confirmação do FACEIO', tags: ['Biometria facial'], parameters: [new OA\Parameter(name: 'WWW-Authenticate', in: 'header', required: true, schema: new OA\Schema(type: 'string'), example: 'Bearer segredo')], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['appId', 'eventName', 'payload', 'facialId'], properties: [new OA\Property(property: 'appId', type: 'string'), new OA\Property(property: 'eventName', type: 'string', enum: ['ENROLL']), new OA\Property(property: 'payload', type: 'string'), new OA\Property(property: 'facialId', type: 'string')])), responses: [new OA\Response(response: 200, description: 'Evento processado.'), new OA\Response(response: 401, description: 'Webhook não autenticado.'), new OA\Response(response: 422, description: 'Evento incompleto ou expirado.')])]
    public function faceioWebhook(): void {}

    #[OA\Get(path: '/time-punch/status', operationId: 'consultarEstadoPonto', summary: 'Consultar ponto de hoje', security: [['bearerAuth' => []]], tags: ['Ponto'], parameters: [new OA\Parameter(name: 'X-Device-ID', in: 'header', required: true, description: 'ID de dispositivo confiável.', schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Estado diário.', content: new OA\JsonContent(ref: '#/components/schemas/RespostaEstadoPonto')), new OA\Response(response: 403, description: 'Aplicativo ou dispositivo sem liberação.')])]
    public function timePunchStatus(): void {}

    #[OA\Post(path: '/time-punch', operationId: 'registrarPonto', summary: 'Registrar próxima batida', description: 'O horário do celular é ignorado; o servidor define data, hora e fuso.', security: [['bearerAuth' => []]], tags: ['Ponto'], parameters: [new OA\Parameter(name: 'X-Device-ID', in: 'header', required: true, schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'Idempotency-Key', in: 'header', required: true, description: 'Valor persistente da intenção, reutilizado até a resposta definitiva.', schema: new OA\Schema(type: 'string', minLength: 16, maxLength: 255), example: 'punch-550e8400-e29b-41d4-a716')], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['expected_type'], properties: [new OA\Property(property: 'expected_type', type: 'string', enum: ['clock_in', 'break_start', 'break_end', 'clock_out'], example: 'clock_in')])), responses: [new OA\Response(response: 201, description: 'Ponto registrado.', content: new OA\JsonContent(ref: '#/components/schemas/RespostaEstadoPonto')), new OA\Response(response: 403, description: 'Aplicativo ou dispositivo sem liberação.'), new OA\Response(response: 409, description: 'A jornada mudou desde a intenção original.'), new OA\Response(response: 422, description: 'Idempotência inválida ou jornada concluída.'), new OA\Response(response: 429, description: 'Limite excedido.')])]
    public function timePunch(): void {}

    #[OA\Get(path: '/time-card', operationId: 'consultarCartaoPonto', summary: 'Consultar cartão mensal', security: [['bearerAuth' => []]], tags: ['Cartão de ponto'], parameters: [new OA\Parameter(name: 'month', in: 'query', required: false, description: 'Mês AAAA-MM; se omitido, usa o atual.', schema: new OA\Schema(type: 'string', pattern: '^\\d{4}-\\d{2}$'), example: '2026-08'), new OA\Parameter(name: 'X-Device-ID', in: 'header', required: true, schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Espelho mensal com jornadas, batidas, totais e saldos.'), new OA\Response(response: 422, description: 'Mês inválido.')])]
    public function timeCard(): void {}

    #[OA\Get(path: '/time-adjustments', operationId: 'listarAjustesPonto', summary: 'Listar meus ajustes', security: [['bearerAuth' => []]], tags: ['Ajustes de ponto'], parameters: [new OA\Parameter(name: 'page', in: 'query', required: false, schema: new OA\Schema(type: 'integer', minimum: 1), example: 1), new OA\Parameter(name: 'X-Device-ID', in: 'header', required: true, schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Lista paginada de ajustes.')])]
    public function timeAdjustments(): void {}

    #[OA\Post(path: '/time-adjustments', operationId: 'solicitarAjustePonto', summary: 'Solicitar ajuste manual', description: 'Toda batida manual nasce pendente e precisa de aprovação do gestor.', security: [['bearerAuth' => []]], tags: ['Ajustes de ponto'], parameters: [new OA\Parameter(name: 'X-Device-ID', in: 'header', required: true, schema: new OA\Schema(type: 'string'))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/SolicitacaoAjuste')), responses: [new OA\Response(response: 201, description: 'Ajuste pendente criado.'), new OA\Response(response: 403, description: 'Sem permissão.'), new OA\Response(response: 422, description: 'Campos, horários ou duplicidade inválidos.')])]
    public function storeTimeAdjustment(): void {}

    #[OA\Get(path: '/time-adjustments/{adjustment}', operationId: 'consultarAjustePonto', summary: 'Consultar um ajuste', security: [['bearerAuth' => []]], tags: ['Ajustes de ponto'], parameters: [new OA\Parameter(name: 'adjustment', in: 'path', required: true, description: 'ID da solicitação.', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'X-Device-ID', in: 'header', required: true, schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Detalhes da solicitação.'), new OA\Response(response: 404, description: 'Solicitação não encontrada.')])]
    public function showTimeAdjustment(): void {}
}

#[OA\Schema(schema: 'InformacoesAplicativo', required: ['version', 'build', 'package_name'], properties: [new OA\Property(property: 'version', type: 'string', example: '1.0.0'), new OA\Property(property: 'build', type: 'string', example: '15'), new OA\Property(property: 'package_name', type: 'string', example: 'br.com.empresa.ponto'), new OA\Property(property: 'signing_digest', type: 'string', nullable: true, example: 'SHA256:...')])]
#[OA\Schema(schema: 'InformacoesAparelho', required: ['platform', 'biometric_available'], properties: [new OA\Property(property: 'platform', type: 'string', enum: ['android', 'ios']), new OA\Property(property: 'manufacturer', type: 'string', nullable: true, example: 'Samsung'), new OA\Property(property: 'model', type: 'string', nullable: true, example: 'SM-S928B'), new OA\Property(property: 'os_version', type: 'string', nullable: true, example: '15'), new OA\Property(property: 'security_patch', type: 'string', format: 'date', nullable: true), new OA\Property(property: 'locale', type: 'string', nullable: true, example: 'pt-BR'), new OA\Property(property: 'timezone', type: 'string', nullable: true, example: 'America/Sao_Paulo'), new OA\Property(property: 'biometric_available', type: 'boolean', example: true)])]
#[OA\Schema(schema: 'AtestacaoAplicativo', required: ['provider', 'token'], properties: [new OA\Property(property: 'provider', type: 'string', enum: ['play_integrity', 'app_attest', 'fake']), new OA\Property(property: 'token', type: 'string', description: 'Token do Play Integrity, App Attest ou driver de testes.')])]
#[OA\Schema(schema: 'RegistroDispositivo', required: ['challenge_id', 'nonce', 'installation_id', 'public_key', 'challenge_signature', 'app', 'device', 'attestation'], properties: [new OA\Property(property: 'challenge_id', type: 'string'), new OA\Property(property: 'nonce', type: 'string'), new OA\Property(property: 'installation_id', type: 'string', format: 'uuid'), new OA\Property(property: 'device_name', type: 'string', nullable: true, example: 'Celular da Ana'), new OA\Property(property: 'public_key', required: ['algorithm', 'value'], properties: [new OA\Property(property: 'algorithm', type: 'string', enum: ['ES256']), new OA\Property(property: 'value', type: 'string', description: 'Chave pública PEM.')], type: 'object'), new OA\Property(property: 'challenge_signature', type: 'string', description: 'Assinatura Base64 do nonce.'), new OA\Property(property: 'app', ref: '#/components/schemas/InformacoesAplicativo'), new OA\Property(property: 'device', ref: '#/components/schemas/InformacoesAparelho'), new OA\Property(property: 'attestation', ref: '#/components/schemas/AtestacaoAplicativo')])]
#[OA\Schema(schema: 'VerificacaoDispositivo', required: ['challenge_id', 'nonce', 'device_id', 'installation_id', 'challenge_signature', 'app', 'device', 'attestation'], properties: [new OA\Property(property: 'challenge_id', type: 'string'), new OA\Property(property: 'nonce', type: 'string'), new OA\Property(property: 'device_id', type: 'string'), new OA\Property(property: 'installation_id', type: 'string', format: 'uuid'), new OA\Property(property: 'challenge_signature', type: 'string'), new OA\Property(property: 'app', ref: '#/components/schemas/InformacoesAplicativo'), new OA\Property(property: 'device', ref: '#/components/schemas/InformacoesAparelho'), new OA\Property(property: 'attestation', ref: '#/components/schemas/AtestacaoAplicativo')])]
#[OA\Schema(schema: 'Dispositivo', properties: [new OA\Property(property: 'id', type: 'string'), new OA\Property(property: 'name', type: 'string', nullable: true), new OA\Property(property: 'platform', type: 'string'), new OA\Property(property: 'manufacturer', type: 'string', nullable: true), new OA\Property(property: 'model', type: 'string', nullable: true), new OA\Property(property: 'status', type: 'string', enum: ['trusted', 'face_verification_required', 'blocked', 'revoked']), new OA\Property(property: 'trusted', type: 'boolean'), new OA\Property(property: 'face_verification_required', type: 'boolean'), new OA\Property(property: 'last_seen_at', type: 'string', format: 'date-time', nullable: true)])]
#[OA\Schema(schema: 'RespostaDispositivo', properties: [new OA\Property(property: 'data', ref: '#/components/schemas/Dispositivo')])]
#[OA\Schema(schema: 'BatidaPonto', properties: [new OA\Property(property: 'id', type: 'integer'), new OA\Property(property: 'type', type: 'string', enum: ['clock_in', 'break_start', 'break_end', 'clock_out', 'overtime_start', 'overtime_end']), new OA\Property(property: 'time', type: 'string', example: '08:00'), new OA\Property(property: 'status', type: 'string', enum: ['approved', 'pending', 'cancelled']), new OA\Property(property: 'reason', type: 'string', nullable: true)])]
#[OA\Schema(schema: 'RespostaEstadoPonto', properties: [new OA\Property(property: 'message', type: 'string', nullable: true), new OA\Property(property: 'data', properties: [new OA\Property(property: 'server_time', type: 'string', format: 'date-time'), new OA\Property(property: 'timezone', type: 'string', example: 'America/Sao_Paulo'), new OA\Property(property: 'next_type', type: 'string', nullable: true), new OA\Property(property: 'registered_type', type: 'string', nullable: true), new OA\Property(property: 'registered_at', type: 'string', nullable: true), new OA\Property(property: 'status', type: 'string', nullable: true), new OA\Property(property: 'reason', type: 'string', nullable: true), new OA\Property(property: 'entries', type: 'array', items: new OA\Items(ref: '#/components/schemas/BatidaPonto')), new OA\Property(property: 'pending_adjustments', type: 'array', items: new OA\Items(type: 'object'))], type: 'object')])]
#[OA\Schema(schema: 'SolicitacaoAjuste', required: ['work_date', 'requested_entries', 'reason'], properties: [new OA\Property(property: 'work_date', type: 'string', format: 'date', example: '2026-08-25', description: 'Data atual ou passada.'), new OA\Property(property: 'requested_entries', type: 'array', minItems: 1, maxItems: 4, items: new OA\Items(required: ['type', 'time'], properties: [new OA\Property(property: 'type', type: 'string', enum: ['clock_in', 'break_start', 'break_end', 'clock_out', 'overtime_start', 'overtime_end'], example: 'clock_out'), new OA\Property(property: 'time', type: 'string', pattern: '^([01]\\d|2[0-3]):[0-5]\\d$', example: '18:00')], type: 'object')), new OA\Property(property: 'reason', type: 'string', minLength: 10, maxLength: 1000, example: 'Esqueci de registrar a saída no horário correto.')])]
class MobileApiSchemas {}
