import { Head, useForm } from '@inertiajs/react';
import { MessageCircle, UserRoundCheck, Video } from 'lucide-react';
import { useRef, useState } from 'react';

type Candidate = { id:number; candidate:{name:string;email:string;phone:string|null}; job:string; disc_profile:string|null; disc_completed_at:string|null };
type Props = { eligibleApplications:Candidate[]; schedules:{data:any[]}; organizers:{id:number;name:string;email:string}[] };

export default function Evaluations({eligibleApplications,schedules,organizers}:Props){
 const [selected,setSelected]=useState<Candidate|null>(null);
 const dialog=useRef<HTMLDialogElement>(null);
 const form=useForm({application_id:'',organizer_id:'',format:'online',title:'Entrevista com RH',starts_at:'',duration_minutes:60,timezone:'America/Sao_Paulo',location:'',meeting_url:'',public_instructions:'',internal_notes:'',send_email:true});
 const choose=(candidate:Candidate)=>{setSelected(candidate);form.clearErrors();form.setData('application_id',String(candidate.id));dialog.current?.showModal();};
 const close=()=>{dialog.current?.close();setSelected(null);form.clearErrors();};
 return <><Head title="Avaliações por candidatura"/><main className="app-page">
  <div className="flex items-center gap-3"><UserRoundCheck/><div><h1 className="text-3xl font-bold">Candidaturas prontas para entrevista</h1><p className="text-base-content/60">Candidatos ativos que concluíram o DISC e estão preparados para a fase 4 — Entrevista com RH.</p></div></div>
  <section className="mt-6"><h2 className="text-xl font-bold">Aguardando agendamento ({eligibleApplications.length})</h2><div className="mt-3 overflow-x-auto rounded-box border border-base-300 bg-base-100"><table className="table"><thead><tr><th>Candidato</th><th>Vaga</th><th>Telefone</th><th>DISC</th><th>Concluído em</th><th className="text-right">Ação</th></tr></thead><tbody>{eligibleApplications.map(c=><tr key={c.id} className={selected?.id===c.id?'bg-primary/5':''}><td><div className="font-bold">{c.candidate.name}</div><div className="text-xs text-base-content/55">{c.candidate.email}</div></td><td>{c.job}</td><td>{c.candidate.phone||'—'}</td><td><div className="flex gap-2"><span className="badge badge-success badge-sm">Concluído</span>{c.disc_profile&&<span className="badge badge-outline badge-sm">Perfil {c.disc_profile}</span>}</div></td><td>{c.disc_completed_at?new Date(c.disc_completed_at).toLocaleString('pt-BR'):'—'}</td><td className="text-right"><button className="btn btn-primary btn-sm" onClick={()=>choose(c)}>Agendar entrevista</button></td></tr>)}{!eligibleApplications.length&&<tr><td colSpan={6} className="py-10 text-center text-base-content/60">Nenhuma candidatura está pronta para a fase 4.</td></tr>}</tbody></table></div></section>
  <dialog ref={dialog} className="modal" onClose={()=>setSelected(null)}>{selected&&<div className="modal-box max-w-3xl"><form className="grid gap-4 md:grid-cols-2" onSubmit={e=>{e.preventDefault();form.post('/hr/evaluations',{preserveScroll:true,onSuccess:close})}}><div className="md:col-span-2"><h2 className="text-xl font-bold">Agendar entrevista com RH</h2><p className="mt-1 text-base-content/65">{selected.candidate.name} · {selected.job}</p></div>
   <select className="select w-full" value={form.data.organizer_id} onChange={e=>form.setData('organizer_id',e.target.value)} required><option value="">Analista organizador</option>{organizers.map(o=><option key={o.id} value={o.id}>{o.name} — {o.email}</option>)}</select>
   <select className="select w-full" value={form.data.format} onChange={e=>form.setData('format',e.target.value)}><option value="online">Online</option><option value="presential">Presencial</option><option value="phone">Telefone</option></select>
   <input className="input w-full" type="datetime-local" value={form.data.starts_at} onChange={e=>form.setData('starts_at',e.target.value)} required/><input className="input w-full" type="number" min="15" max="240" value={form.data.duration_minutes} onChange={e=>form.setData('duration_minutes',Number(e.target.value))}/>
   {form.data.format==='online'?<input className="input w-full md:col-span-2" placeholder="Link do Google Meet" value={form.data.meeting_url} onChange={e=>form.setData('meeting_url',e.target.value)} required/>:<input className="input w-full md:col-span-2" placeholder="Local/endereço" value={form.data.location} onChange={e=>form.setData('location',e.target.value)}/>}
   <textarea className="textarea md:col-span-2 w-full" placeholder="Instruções para o candidato" value={form.data.public_instructions} onChange={e=>form.setData('public_instructions',e.target.value)}/><label className="label md:col-span-2"><input type="checkbox" className="checkbox" checked={form.data.send_email} onChange={e=>form.setData('send_email',e.target.checked)}/> Enviar convite por e-mail</label>{Object.values(form.errors).length>0&&<div className="alert alert-error md:col-span-2">{Object.values(form.errors).join(' ')}</div>}<div className="modal-action md:col-span-2"><button type="button" className="btn btn-ghost" onClick={close}>Cancelar</button><button className="btn btn-primary" disabled={form.processing}>{form.processing&&<span className="loading loading-spinner loading-sm"/>}Confirmar agendamento</button></div>
  </form></div>}<form method="dialog" className="modal-backdrop"><button onClick={()=>setSelected(null)}>Fechar</button></form></dialog>
  <section className="mt-8"><h2 className="text-xl font-bold">Entrevistas agendadas</h2><div className="mt-3 overflow-x-auto rounded-box border border-base-300 bg-base-100"><table className="table"><thead><tr><th>Candidato</th><th>Vaga/fase</th><th>Data</th><th>Organizador</th><th>Resposta</th><th className="text-right">Ações</th></tr></thead><tbody>{schedules.data.map(s=><tr key={s.id}><td className="font-bold">{s.candidate.name}</td><td><div>{s.job}</div><div className="text-xs text-base-content/55">{s.stage}</div></td><td>{new Date(s.starts_at).toLocaleString('pt-BR')}</td><td>{s.organizer}</td><td><span className="badge badge-outline badge-sm">{s.candidate_response}</span></td><td><div className="flex justify-end gap-2">{s.meeting_url&&<a className="btn btn-sm btn-primary" href={s.meeting_url} target="_blank" rel="noreferrer"><Video/>Reunião</a>}{s.whatsapp_url&&<a className="btn btn-sm btn-success" href={s.whatsapp_url} target="_blank" rel="noopener noreferrer"><MessageCircle/>WhatsApp</a>}</div></td></tr>)}</tbody></table></div></section>
 </main></>;
}
